### ISSUE TITLE
Possible Redundandcy of code ?

### ISSUE THREAD

**Issue by ajitjha393** [ghinda/durruti#1]
https://github.com/ghinda/durruti/blob/a67a95e9a636367b43afffdbede1ba083be00ebe/src/dom.js#L61

Hey I was building a virtual DOM similar as of yours and came across your Repo
I was reading your code and I can't understand usage of this piece of code.
Could you elaborate on that?

**Comment by ajitjha393** [comment]
![image](https://user-images.githubusercontent.com/42679346/92361770-8b77b080-f10c-11ea-9f22-491bdef43d59.png)
I think the condition you r trying to check here is already handled in above if-else check...
Am I missing something ?

**Comment by ghinda** [comment]
I haven't worked on it for a while, but judging from the comment above it, I believe it's for properties like `checked` that don't reflect user changes in `getAttribute`: 

[siloz.io checked getAttribute demo](https://www.siloz.io/#s=N4IgbgpgTgzglgewHYgFwEYA0IBmcA2EMaA2qAC4CeADhGiABbkC2+I2AxsuREufQB44SagFdyAAiq0AvAB0QHBhA4BrAEYIAHgolKVqiABN5IclFEQFAPhABfTBRp1UimMU7de-V-cdnnegArD0UvPnouJBhJABJ9NU0tCRkJIwQOUWZvADoAR0soSgBlCEIOcgQoAAoAcmExclqASjkkNvjlRO0cgEMjIwBRSD4AGTgY3mg6pV6kAHMIWswJaohmlOsJYDaJPWQYBEIc-AR5tZzyXqhF8hyEwyNWpD2ow+PT84hL69uc24AguRzHB1OIIDMuo8Ws87M17ABdbDUfCiebCYioEhIszKbL0d7XOAAL2MEnwcHmTHYIGocyIaFAHHcjMYcAGvDQ5ksDkYLDYqGAvJCjLsYqAA)

**Comment by ajitjha393** [comment]
Ohh Shoots got it ... I really didn't new that such boolean props attributes changed values are not reflected in `getAttribute`:
Thanks for clarifying !

**Comment by ghinda** [comment]
No problem. Good luck with the vdom!
